"""Run the paper audit; retain mismatches and write reproducible artifacts."""

import argparse
import csv
import json
import os
from collections import Counter
from pathlib import Path

from src.audit import DATASETS, Checkpoint, audit_all


def write_reports(checks: list[Checkpoint], traces: dict, output: Path) -> None:
    output.mkdir(parents=True,exist_ok=True)
    records = [check.record() for check in checks]
    with (output / "checkpoints.csv").open("w",encoding="utf-8",newline="") as handle:
        writer = csv.DictWriter(handle,fieldnames=list(records[0]))
        writer.writeheader()
        writer.writerows(records)
    (output / "audit.json").write_text(json.dumps(
        {"counts":dict(Counter(c.status for c in checks)),"checkpoints":records,"traces":traces},
        indent=2,ensure_ascii=False,allow_nan=False),encoding="utf-8")
    lines = ["# Paper numerical audit", "",
             "Generated by `python reproduce.py`. FAIL means a published checkpoint does not match;",
             "UNRESOLVED means a source ambiguity or upstream failure prevents evaluation.",
             "Primary strict numeric tolerance is 1e-4. Source-precision status is a separate column.",
             "Rounded and baseline interpretation modes are not substitutes for full precision.", "",
             "## Coverage summary", "",
             "| Section / mode | PASS | FAIL | UNRESOLVED | Max numeric error |",
             "|---|---:|---:|---:|---:|"]
    sections = list(dict.fromkeys((c.section,c.mode) for c in checks))
    for section,mode in sections:
        group = [c for c in checks if (c.section,c.mode)==(section,mode)]
        count = Counter(c.status for c in group)
        maximum = max((c.error for c in group if c.error is not None),default=0)
        lines.append(f"| {section} / {mode} | {count['PASS']} | {count['FAIL']} | {count['UNRESOLVED']} | {maximum:.12g} |")
    for section,mode in sections:
        lines.extend(["",f"## {section} — {mode}","",
                      "| Checkpoint | Paper | Code | Abs error | Strict | Source precision | Note |",
                      "|---|---|---|---|---|---|---|"])
        for c in checks:
            if (c.section,c.mode)!=(section,mode):
                continue
            error = "—" if c.error is None else f"{c.error:.12g}"
            actual = "UNRESOLVED" if c.code is None else (f"{c.code:.12g}" if isinstance(c.code,float) else str(c.code))
            lines.append(f"| {c.name} | {c.paper} | {actual} | {error} | {c.status} | {c.display_status} | {c.note} |")
    lines.extend(["","## HWM from printed intermediates — diagnostic only","",
                  "These calculations use printed matrix/weights, not original IVFFNs; they are excluded from checkpoint totals.",
                  "", "| Dataset / alternative | Paper final | HWM of printed values | Abs error |",
                  "|---|---:|---:|---:|"])
    for label,d in DATASETS.items():
        for i,(expected,actual) in enumerate(zip(d.PAPER_FINAL_SCORES,
                traces["proposed"][label]["HWM_from_printed_intermediates"]),1):
            lines.append(f"| {label} / p{i} | {expected} | {actual:.12g} | {abs(expected-actual):.12g} |")
    diag = traces["example3_diagnostics"]
    lines.extend(["","## Example 3 notation/substitution diagnostics","",
                  "Neither diagnostic changes the solver. The printed p2 weights sum to 1.01.","",
                  "| Interpretation | Paper final | Code | Abs error |", "|---|---:|---:|---:|"])
    for name,expected,actual in [
        ("Eq25 literal crisp / p1",.0398,diag["Eq25_literal_crisp_eta"][0]),
        ("Eq25 literal crisp / p2",.0301,diag["Eq25_literal_crisp_eta"][1]),
        ("Printed inconsistent p2 substitution",.0301,diag["printed_p2_eta"]),
    ]:
        lines.append(f"| {name} | {expected} | {actual:.12g} | {abs(expected-actual):.12g} |")
    discrepancy_path = os.path.relpath(Path(__file__).resolve().parent/"DISCREPANCIES.md",output.resolve()).replace("\\","/")
    lines.extend(["","## Full intermediate traces","",
                  "See [audit.json](audit.json), including both baseline interpretations, rounded stages,",
                  f"and HWM evaluated from printed intermediates. See [DISCREPANCIES.md]({discrepancy_path})",
                  "for source ambiguities, domains, and provenance."])
    (output / "reproduction.md").write_text("\n".join(lines)+"\n",encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--section",help="Exact report section, e.g. 'Case 1', 'Example 10', 'Table 4'")
    parser.add_argument("--output-dir",type=Path,default=Path("reports"))
    parser.add_argument("--plots",action="store_true",help="Export comparison plots (requires requirements-plots.txt)")
    args = parser.parse_args()
    checks,traces = audit_all()
    if args.section:
        checks = [c for c in checks if c.section==args.section]
        if not checks:
            parser.error(f"unknown section: {args.section}")
    write_reports(checks,traces,args.output_dir)
    if args.plots:
        from src.plots import export_plots
        export_plots(traces,args.output_dir)
    for section,mode in dict.fromkeys((c.section,c.mode) for c in checks):
        print(f"\n=== {section} / {mode} ===")
        for c in checks:
            if (c.section,c.mode)==(section,mode):
                error = "-" if c.error is None else f"{c.error:.12g}"
                actual = f"{c.code:.12g}" if isinstance(c.code,float) else str(c.code)
                print(f"{c.name}: paper={c.paper} code={actual} abs_error={error} {c.status}")
    print("\nCounts:",dict(Counter(c.status for c in checks)))
    print("Artifacts:",args.output_dir.resolve())
    failed = any(c.status != "PASS" for c in checks)
    print("Audit complete; mismatches and source ambiguities remain visible. This is not an all-match reproduction."
          if failed else "All selected checkpoints PASS at the stated tolerances.")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
